export const withSlug = (slug: string, path: string) => `/${slug}${path}`;

import {
  Home,
  CalendarTick,
  Profile2User,
  Calendar,
  Chart,
  TaskSquare,
  Category2,
  DiscountShape,
  Flash,
  Setting2,
  Grid2,
  GlobalSearch,
  PercentageSquare,
  Facebook,
  Moneys,
  ScanBarcode,
  Location,
  Clock,
  User,
  Setting,
  Card,
  Lock,
  MonitorMobbile,
  Grid7,
  Element,
  Menu,
  Document,
  Calendar2,
  CalendarAdd,
  CalendarEdit
} from "iconsax-react";

const SIDEBAR_LINKS = [
  { label: "Dashboard", href: "/dashboard", icon: <Home /> },
  { label: "Appointments", href: "/appointments", icon: <CalendarTick /> },
  { label: "Customers", href: "/customers", icon: <Profile2User /> },
  { label: "Calendar", href: "/calendar", icon: <Calendar /> },
  { label: "Reports", href: "/reports", icon: <Chart /> },
  { label: "Department", href: "/departments", icon: <Category2 /> },
  { label: "Categories", href: "/categories", icon: <Grid2 /> },
  { label: "Employees", href: "/employees", icon: <Profile2User /> },

  // 🔐 SERVICE TYPE BASED (IMPORTANT)
  {
    label: "Menu Settings",
    icon: <Calendar2 />,
    serviceType: 2, // HOTEL
    children: [
      { label: "Menus", href: "/menu-settings/menus" },
      { label: "Item Categories", href: "/menu-settings/item-categories" },
      { label: "Table Settings", href: "/menu-settings/table-settings" },
    ],
  },
  {
    label: "Appointment Settings",
    href: "/oth-opts",
    icon: <CalendarAdd />,
    serviceType: 3, // OTHER
  },
  {
    label: "Appointment Settings",
    href: "/hos-opts",
    icon: <CalendarEdit />,
    serviceType: 1, // HOSPITAL
  },

  { label: "Coupons", href: "/coupons", icon: <DiscountShape /> },
  { label: "Upgrade Plan", href: "/all-plans", icon: <Moneys /> },
  { label: "Purchase History", href: "/purchase-history", icon: <Document /> },
  // Futeye Update Plugins
  // { label: "Plugins", href: "/plugins", icon: <Flash /> },
  { label: "Settings", href: "/settings", icon: <Setting2 /> },
  { label: "Website Setup", href: "/website-setup", icon: <MonitorMobbile /> },
];

const MY_ACCOUNT_DROPDOWN_OPTIONS = [
  {
    label: "Profile",
    icon: <User />,
    href: "/settings/profile",
  },
  {
    label: "Site Settings",
    icon: <Setting />,
    href: "/settings",
  },
  {
    label: "Billing & Invoices",
    icon: <Card />,
    href: "/",
  },
];


const SETTINGS_LINKS = [
  { label: "Profile Settings", href: "/settings/profile", icon: <User /> },
  { label: "Change Password", href: "/settings/change-password", icon: <Lock /> },
  { label: "Basic Settings", href: "/settings", icon: <Setting2 /> },
  { label: "SEO Settings", href: "/settings/seo", icon: <GlobalSearch /> },
  { label: "Tax Settings", href: "/settings/tax", icon: <PercentageSquare /> },
  { label: "Social Settings", href: "/settings/social", icon: <Facebook /> },
  { label: "Payment Settings", href: "/settings/payment", icon: <Moneys /> },
  { label: "QR Code", href: "/settings/qr-code", icon: <ScanBarcode /> },

];


const WEBSITE_SETUP_LINKS = [
  {
    label: "Templates",
    href: "/website-setup",
    icon: <Element />,
  },
  {
    label: "Homepage Settings",
    href: "/website-setup/homepage",
    icon: <Grid7 />,
  },
  {
    label: "Header Settings",
    href: "/website-setup/header",
    icon: <Menu />,
  },
  {
    label: "Pages",
    href: "/website-setup/pages",
    icon: <Document />,
  },
  {
    label: "Domain Request",
    href: "/website-setup/domain-request",
    icon: <GlobalSearch />,
  },
];

const APPOINTMENT_STATUS = [
  {
    label: "Booked",
    value: "Booked",
  },
  {
    label: "Processing",
    value: "Processing",
  },
  {
    label: "Completed",
    value: "Completed",
  },
  {
    label: "Cancelled",
    value: "Cancelled",
  },
];

const PAYMENT_STATUS = [
  {
    label: "Paid",
    value: "Paid",
  },
  {
    label: "Unpaid",
    value: "Unpaid",
  },
];

const PAYMENT_METHODS = [
  {
    label: "Cash In Hand",
    value: "Cash In Hand",
  },
  {
    label: "Bank Transfer",
    value: "Bank Transfer",
  },
  {
    label: "Razorpay",
    value: "Razorpay",
  },
  {
    label: "PhonePe",
    value: "PhonePe",
  },
];


//------------------------------------------------

const PAGINATION_PER_PAGE = [10, 25, 50, 100];

const COUNTRIES = [
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AS", label: "American Samoa" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "AI", label: "Anguilla" },
  { value: "AQ", label: "Antarctica" },
  { value: "AG", label: "Antigua and Barbuda" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AW", label: "Aruba" },
  { value: "AU", label: "Australia" },
  { value: "AT", label: "Austria" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "BS", label: "Bahamas (the)" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesh" },
  { value: "BB", label: "Barbados" },
  { value: "BY", label: "Belarus" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BM", label: "Bermuda" },
  { value: "BT", label: "Bhutan" },
  {
    value: "BO",
    label: "Bolivia (Plurinational State of)",
  },
  {
    value: "BQ",
    label: "Bonaire, Sint Eustatius and Saba",
  },
  { value: "BA", label: "Bosnia and Herzegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BV", label: "Bouvet Island" },
  { value: "BR", label: "Brazil" },
  {
    value: "IO",
    label: "British Indian Ocean Territory (the)",
  },
  { value: "BN", label: "Brunei Darussalam" },
  { value: "BG", label: "Bulgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "CV", label: "Cabo Verde" },
  { value: "KH", label: "Cambodia" },
  { value: "CM", label: "Cameroon" },
  { value: "CA", label: "Canada" },
  { value: "KY", label: "Cayman Islands (the)" },
  {
    value: "CF",
    label: "Central African Republic (the)",
  },
  { value: "TD", label: "Chad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CX", label: "Christmas Island" },
  {
    value: "CC",
    label: "Cocos (Keeling) Islands (the)",
  },
  { value: "CO", label: "Colombia" },
  { value: "KM", label: "Comoros (the)" },
  {
    value: "CD",
    label: "Congo (the Democratic Republic of the)",
  },
  { value: "CG", label: "Congo (the)" },
  { value: "CK", label: "Cook Islands (the)" },
  { value: "CR", label: "Costa Rica" },
  { value: "HR", label: "Croatia" },
  { value: "CU", label: "Cuba" },
  { value: "CW", label: "Curaçao" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czechia" },
  { value: "CI", label: "Côte d'Ivoire" },
  { value: "DK", label: "Denmark" },
  { value: "DJ", label: "Djibouti" },
  { value: "DM", label: "Dominica" },
  { value: "DO", label: "Dominican Republic (the)" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egypt" },
  { value: "SV", label: "El Salvador" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estonia" },
  { value: "SZ", label: "Eswatini" },
  { value: "ET", label: "Ethiopia" },
  {
    value: "FK",
    label: "Falkland Islands (the) [Malvinas]",
  },
  { value: "FO", label: "Faroe Islands (the)" },
  { value: "FJ", label: "Fiji" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "GF", label: "French Guiana" },
  { value: "PF", label: "French Polynesia" },
  {
    value: "TF",
    label: "French Southern Territories (the)",
  },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia (the)" },
  { value: "GE", label: "Georgia" },
  { value: "DE", label: "Germany" },
  { value: "GH", label: "Ghana" },
  { value: "GI", label: "Gibraltar" },
  { value: "GR", label: "Greece" },
  { value: "GL", label: "Greenland" },
  { value: "GD", label: "Grenada" },
  { value: "GP", label: "Guadeloupe" },
  { value: "GU", label: "Guam" },
  { value: "GT", label: "Guatemala" },
  { value: "GG", label: "Guernsey" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bissau" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haiti" },
  {
    value: "HM",
    label: "Heard Island and McDonald Islands",
  },
  { value: "VA", label: "Holy See (the)" },
  { value: "HN", label: "Honduras" },
  { value: "HK", label: "Hong Kong" },
  { value: "HU", label: "Hungary" },
  { value: "IS", label: "Iceland" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  {
    value: "IR",
    label: "Iran (Islamic Republic of)",
  },
  { value: "IQ", label: "Iraq" },
  { value: "IE", label: "Ireland" },
  { value: "IM", label: "Isle of Man" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italy" },
  { value: "JM", label: "Jamaica" },
  { value: "JP", label: "Japan" },
  { value: "JE", label: "Jersey" },
  { value: "JO", label: "Jordan" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "KE", label: "Kenya" },
  { value: "KI", label: "Kiribati" },
  {
    value: "KP",
    label: "Korea (the Democratic People's Republic of)",
  },
  { value: "KR", label: "Korea (the Republic of)" },
  { value: "KW", label: "Kuwait" },
  { value: "KG", label: "Kyrgyzstan" },
  {
    value: "LA",
    label: "Lao People's Democratic Republic (the)",
  },
  { value: "LV", label: "Latvia" },
  { value: "LB", label: "Lebanon" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libya" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Lithuania" },
  { value: "LU", label: "Luxembourg" },
  { value: "MO", label: "Macao" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malaysia" },
  { value: "MV", label: "Maldives" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Malta" },
  { value: "MH", label: "Marshall Islands (the)" },
  { value: "MQ", label: "Martinique" },
  { value: "MR", label: "Mauritania" },
  { value: "MU", label: "Mauritius" },
  { value: "YT", label: "Mayotte" },
  { value: "MX", label: "Mexico" },
  {
    value: "FM",
    label: "Micronesia (Federated States of)",
  },
  {
    value: "MD",
    label: "Moldova (the Republic of)",
  },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongolia" },
  { value: "ME", label: "Montenegro" },
  { value: "MS", label: "Montserrat" },
  { value: "MA", label: "Morocco" },
  { value: "MZ", label: "Mozambique" },
  { value: "MM", label: "Myanmar" },
  { value: "NA", label: "Namibia" },
  { value: "NR", label: "Nauru" },
  { value: "NP", label: "Nepal" },
  { value: "NL", label: "Netherlands (the)" },
  { value: "NC", label: "New Caledonia" },
  { value: "NZ", label: "New Zealand" },
  { value: "NI", label: "Nicaragua" },
  { value: "NE", label: "Niger (the)" },
  { value: "NG", label: "Nigeria" },
  { value: "NU", label: "Niue" },
  { value: "NF", label: "Norfolk Island" },
  {
    value: "MP",
    label: "Northern Mariana Islands (the)",
  },
  { value: "NO", label: "Norway" },
  { value: "OM", label: "Oman" },
  { value: "PK", label: "Pakistan" },
  { value: "PW", label: "Palau" },
  { value: "PS", label: "Palestine, State of" },
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Papua New Guinea" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippines (the)" },
  { value: "PN", label: "Pitcairn" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "PR", label: "Puerto Rico" },
  { value: "QA", label: "Qatar" },
  {
    value: "MK",
    label: "Republic of North Macedonia",
  },
  { value: "RO", label: "Romania" },
  { value: "RU", label: "Russian Federation (the)" },
  { value: "RW", label: "Rwanda" },
  { value: "RE", label: "Réunion" },
  { value: "BL", label: "Saint Barthélemy" },
  {
    value: "SH",
    label: "Saint Helena, Ascension and Tristan da Cunha",
  },
  { value: "KN", label: "Saint Kitts and Nevis" },
  { value: "LC", label: "Saint Lucia" },
  {
    value: "MF",
    label: "Saint Martin (French part)",
  },
  {
    value: "PM",
    label: "Saint Pierre and Miquelon",
  },
  {
    value: "VC",
    label: "Saint Vincent and the Grenadines",
  },
  { value: "WS", label: "Samoa" },
  { value: "SM", label: "San Marino" },
  { value: "ST", label: "Sao Tome and Principe" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SN", label: "Senegal" },
  { value: "RS", label: "Serbia" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leone" },
  { value: "SG", label: "Singapore" },
  {
    value: "SX",
    label: "Sint Maarten (Dutch part)",
  },
  { value: "SK", label: "Slovakia" },
  { value: "SI", label: "Slovenia" },
  { value: "SB", label: "Solomon Islands" },
  { value: "SO", label: "Somalia" },
  { value: "ZA", label: "South Africa" },
  {
    value: "GS",
    label: "South Georgia and the South Sandwich Islands",
  },
  { value: "SS", label: "South Sudan" },
  { value: "ES", label: "Spain" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SD", label: "Sudan (the)" },
  { value: "SR", label: "Suriname" },
  { value: "SJ", label: "Svalbard and Jan Mayen" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "SY", label: "Syrian Arab Republic" },
  { value: "TW", label: "Taiwan" },
  { value: "TJ", label: "Tajikistan" },
  {
    value: "TZ",
    label: "Tanzania, United Republic of",
  },
  { value: "TH", label: "Thailand" },
  { value: "TL", label: "Timor-Leste" },
  { value: "TG", label: "Togo" },
  { value: "TK", label: "Tokelau" },
  { value: "TO", label: "Tonga" },
  { value: "TT", label: "Trinidad and Tobago" },
  { value: "TN", label: "Tunisia" },
  { value: "TR", label: "Turkey" },
  { value: "TM", label: "Turkmenistan" },
  {
    value: "TC",
    label: "Turks and Caicos Islands (the)",
  },
  { value: "TV", label: "Tuvalu" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukraine" },
  {
    value: "AE",
    label: "United Arab Emirates (the)",
  },
  {
    value: "GB",
    label: "United Kingdom of Great Britain and Northern Ireland (the)",
  },
  {
    value: "UM",
    label: "United States Minor Outlying Islands (the)",
  },
  {
    value: "US",
    label: "United States of America (the)",
  },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Uzbekistan" },
  { value: "VU", label: "Vanuatu" },
  {
    value: "VE",
    label: "Venezuela (Bolivarian Republic of)",
  },
  { value: "VN", label: "Viet Nam" },
  { value: "VG", label: "Virgin Islands (British)" },
  { value: "VI", label: "Virgin Islands (U.S.)" },
  { value: "WF", label: "Wallis and Futuna" },
  { value: "EH", label: "Western Sahara" },
  { value: "YE", label: "Yemen" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" },
  { value: "AX", label: "Åland Islands" },
];

const INTERVAL_TYPES = [
  {
    value: "minutes",
    label: "Minutes",
  },
  {
    value: "hours",
    label: "Hours",
  },
];

const GST_PERCENTAGES = [
  {
    value: "0",
    label: "0%",
  },
  {
    value: "0.25",
    label: "0.25%",
  },
  {
    value: "3",
    label: "3%",
  },
  {
    value: "5",
    label: "5%",
  },
  {
    value: "12",
    label: "12%",
  },
  {
    value: "18",
    label: "18%",
  },
  {
    value: "28",
    label: "28%",
  },
];

const GST_TYPES = [
  {
    value: "inclusive",
    label: "Inclusive of tax",
  },
  {
    value: "exclusive",
    label: "Exclusive of tax",
  },
];

const DISCOUNT_TYPE = [
  {
    value: "percentage",
    label: "Percentage",
  },
  {
    value: "fixed",
    label: "Fixed",
  },
];

const COLOR_MAP = [
  { char: "a", color: "bg-[red]" },
  { char: "b", color: "bg-[green]" },
  { char: "c", color: "bg-[blue]" },
  { char: "d", color: "bg-[orange]" },
  { char: "e", color: "bg-[purple]" },
  { char: "f", color: "bg-[yellow]" },
  { char: "g", color: "bg-[pink]" },
  { char: "h", color: "bg-[brown]" },
  { char: "i", color: "bg-[turquoise]" },
  { char: "j", color: "bg-[navy]" },
  { char: "k", color: "bg-[lavender]" },
  { char: "l", color: "bg-[olive]" },
  { char: "m", color: "bg-[teal]" },
  { char: "n", color: "bg-[salmon]" },
  { char: "o", color: "bg-[maroon]" },
  { char: "p", color: "bg-[aqua]" },
  { char: "q", color: "bg-[lime]" },
  { char: "r", color: "bg-[indigo]" },
  { char: "s", color: "bg-[coral]" },
  { char: "t", color: "bg-[fuschia]" },
  { char: "u", color: "bg-[chartreuse]" },
  { char: "v", color: "bg-[plum]" },
  { char: "w", color: "bg-[sienna]" },
  { char: "x", color: "bg-[slate]" },
  { char: "y", color: "bg-[crimson]" },
  { char: "z", color: "bg-[azure]" },
];

const CURRENCIES = [
  { code: "AED", name: "United Arab Emirates dirham" },
  { code: "AFN", name: "Afghan afghani" },
  { code: "ALL", name: "Albanian lek" },
  { code: "AMD", name: "Armenian dram" },
  { code: "ANG", name: "Netherlands Antillean guilder" },
  { code: "AOA", name: "Angolan kwanza" },
  { code: "ARS", name: "Argentine peso" },
  { code: "AUD", name: "Australian dollar" },
  { code: "AWG", name: "Aruban florin" },
  { code: "AZN", name: "Azerbaijani manat" },
  {
    code: "BAM",
    name: "Bosnia and Herzegovina convertible mark",
  },
  { code: "BBD", name: "Barbados dollar" },
  { code: "BDT", name: "Bangladeshi taka" },
  { code: "BGN", name: "Bulgarian lev" },
  { code: "BHD", name: "Bahraini dinar" },
  { code: "BIF", name: "Burundian franc" },
  { code: "BMD", name: "Bermudian dollar" },
  { code: "BND", name: "Brunei dollar" },
  { code: "BOB", name: "Boliviano" },
  { code: "BRL", name: "Brazilian real" },
  { code: "BSD", name: "Bahamian dollar" },
  { code: "BTN", name: "Bhutanese ngultrum" },
  { code: "BWP", name: "Botswana pula" },
  { code: "BYN", name: "New Belarusian ruble" },
  { code: "BYR", name: "Belarusian ruble" },
  { code: "BZD", name: "Belize dollar" },
  { code: "CAD", name: "Canadian dollar" },
  { code: "CDF", name: "Congolese franc" },
  { code: "CHF", name: "Swiss franc" },
  { code: "CLF", name: "Unidad de Fomento" },
  { code: "CLP", name: "Chilean peso" },
  { code: "CNY", name: "Renminbi|Chinese yuan" },
  { code: "COP", name: "Colombian peso" },
  { code: "CRC", name: "Costa Rican colon" },
  { code: "CUC", name: "Cuban convertible peso" },
  { code: "CUP", name: "Cuban peso" },
  { code: "CVE", name: "Cape Verde escudo" },
  { code: "CZK", name: "Czech koruna" },
  { code: "DJF", name: "Djiboutian franc" },
  { code: "DKK", name: "Danish krone" },
  { code: "DOP", name: "Dominican peso" },
  { code: "DZD", name: "Algerian dinar" },
  { code: "EGP", name: "Egyptian pound" },
  { code: "ERN", name: "Eritrean nakfa" },
  { code: "ETB", name: "Ethiopian birr" },
  { code: "EUR", name: "Euro" },
  { code: "FJD", name: "Fiji dollar" },
  { code: "FKP", name: "Falkland Islands pound" },
  { code: "GBP", name: "Pound sterling" },
  { code: "GEL", name: "Georgian lari" },
  { code: "GHS", name: "Ghanaian cedi" },
  { code: "GIP", name: "Gibraltar pound" },
  { code: "GMD", name: "Gambian dalasi" },
  { code: "GNF", name: "Guinean franc" },
  { code: "GTQ", name: "Guatemalan quetzal" },
  { code: "GYD", name: "Guyanese dollar" },
  { code: "HKD", name: "Hong Kong dollar" },
  { code: "HNL", name: "Honduran lempira" },
  { code: "HRK", name: "Croatian kuna" },
  { code: "HTG", name: "Haitian gourde" },
  { code: "HUF", name: "Hungarian forint" },
  { code: "IDR", name: "Indonesian rupiah" },
  { code: "ILS", name: "Israeli new shekel" },
  { code: "INR", name: "Indian rupee" },
  { code: "IQD", name: "Iraqi dinar" },
  { code: "IRR", name: "Iranian rial" },
  { code: "ISK", name: "Icelandic króna" },
  { code: "JMD", name: "Jamaican dollar" },
  { code: "JOD", name: "Jordanian dinar" },
  { code: "JPY", name: "Japanese yen" },
  { code: "KES", name: "Kenyan shilling" },
  { code: "KGS", name: "Kyrgyzstani som" },
  { code: "KHR", name: "Cambodian riel" },
  { code: "KMF", name: "Comoro franc" },
  { code: "KPW", name: "North Korean won" },
  { code: "KRW", name: "South Korean won" },
  { code: "KWD", name: "Kuwaiti dinar" },
  { code: "KYD", name: "Cayman Islands dollar" },
  { code: "KZT", name: "Kazakhstani tenge" },
  { code: "LAK", name: "Lao kip" },
  { code: "LBP", name: "Lebanese pound" },
  { code: "LKR", name: "Sri Lankan rupee" },
  { code: "LRD", name: "Liberian dollar" },
  { code: "LSL", name: "Lesotho loti" },
  { code: "LYD", name: "Libyan dinar" },
  { code: "MAD", name: "Moroccan dirham" },
  { code: "MDL", name: "Moldovan leu" },
  { code: "MGA", name: "Malagasy ariary" },
  { code: "MKD", name: "Macedonian denar" },
  { code: "MMK", name: "Myanmar kyat" },
  { code: "MNT", name: "Mongolian tögrög" },
  { code: "MOP", name: "Macanese pataca" },
  { code: "MRO", name: "Mauritanian ouguiya" },
  { code: "MUR", name: "Mauritian rupee" },
  { code: "MVR", name: "Maldivian rufiyaa" },
  { code: "MWK", name: "Malawian kwacha" },
  { code: "MXN", name: "Mexican peso" },
  { code: "MXV", name: "Mexican Unidad de Inversion" },
  { code: "MYR", name: "Malaysian ringgit" },
  { code: "MZN", name: "Mozambican metical" },
  { code: "NAD", name: "Namibian dollar" },
  { code: "NGN", name: "Nigerian naira" },
  { code: "NIO", name: "Nicaraguan córdoba" },
  { code: "NOK", name: "Norwegian krone" },
  { code: "NPR", name: "Nepalese rupee" },
  { code: "NZD", name: "New Zealand dollar" },
  { code: "OMR", name: "Omani rial" },
  { code: "PAB", name: "Panamanian balboa" },
  { code: "PEN", name: "Peruvian Sol" },
  { code: "PGK", name: "Papua New Guinean kina" },
  { code: "PHP", name: "Philippine peso" },
  { code: "PKR", name: "Pakistani rupee" },
  { code: "PLN", name: "Polish złoty" },
  { code: "PYG", name: "Paraguayan guaraní" },
  { code: "QAR", name: "Qatari riyal" },
  { code: "RON", name: "Romanian leu" },
  { code: "RSD", name: "Serbian dinar" },
  { code: "RUB", name: "Russian ruble" },
  { code: "RWF", name: "Rwandan franc" },
  { code: "SAR", name: "Saudi riyal" },
  { code: "SBD", name: "Solomon Islands dollar" },
  { code: "SCR", name: "Seychelles rupee" },
  { code: "SDG", name: "Sudanese pound" },
  { code: "SEK", name: "Swedish krona" },
  { code: "SGD", name: "Singapore dollar" },
  { code: "SHP", name: "Saint Helena pound" },
  { code: "SLL", name: "Sierra Leonean leone" },
  { code: "SOS", name: "Somali shilling" },
  { code: "SRD", name: "Surinamese dollar" },
  { code: "SSP", name: "South Sudanese pound" },
  { code: "STD", name: "São Tomé and Príncipe dobra" },
  { code: "SVC", name: "Salvadoran colón" },
  { code: "SYP", name: "Syrian pound" },
  { code: "SZL", name: "Swazi lilangeni" },
  { code: "THB", name: "Thai baht" },
  { code: "TJS", name: "Tajikistani somoni" },
  { code: "TMT", name: "Turkmenistani manat" },
  { code: "TND", name: "Tunisian dinar" },
  { code: "TOP", name: "Tongan paʻanga" },
  { code: "TRY", name: "Turkish lira" },
  { code: "TTD", name: "Trinidad and Tobago dollar" },
  { code: "TWD", name: "New Taiwan dollar" },
  { code: "TZS", name: "Tanzanian shilling" },
  { code: "UAH", name: "Ukrainian hryvnia" },
  { code: "UGX", name: "Ugandan shilling" },
  { code: "USD", name: "United States dollar" },
  { code: "UYI", name: "Uruguay Peso en Unidades Indexadas" },
  { code: "UYU", name: "Uruguayan peso" },
  { code: "UZS", name: "Uzbekistan som" },
  { code: "VEF", name: "Venezuelan bolívar" },
  { code: "VND", name: "Vietnamese đồng" },
  { code: "VUV", name: "Vanuatu vatu" },
  { code: "WST", name: "Samoan tala" },
  { code: "XAF", name: "Central African CFA franc" },
  { code: "XCD", name: "East Caribbean dollar" },
  { code: "XOF", name: "West African CFA franc" },
  { code: "XPF", name: "CFP franc" },
  { code: "XXX", name: "No currency" },
  { code: "YER", name: "Yemeni rial" },
  { code: "ZAR", name: "South African rand" },
  { code: "ZMW", name: "Zambian kwacha" },
  { code: "ZWL", name: "Zimbabwean dollar" },
];

const REPORTS_DATE = [
  {
    value: "all",
    label: "All Time",
  },
  {
    value: "today",
    label: "Today",
  },
  {
    value: "yesterday",
    label: "Yesterday",
  },
  {
    value: "thisWeek",
    label: "This Week",
  },
  {
    value: "thisMonth",
    label: "This Month",
  },
  {
    value: "thisYear",
    label: "This Year",
  },
];


export {
  SIDEBAR_LINKS,
  WEBSITE_SETUP_LINKS,
  MY_ACCOUNT_DROPDOWN_OPTIONS,
  APPOINTMENT_STATUS,
  PAYMENT_STATUS,
  PAYMENT_METHODS,
  PAGINATION_PER_PAGE,
  COUNTRIES,
  INTERVAL_TYPES,
  GST_PERCENTAGES,
  GST_TYPES,
  DISCOUNT_TYPE,
  COLOR_MAP,
  SETTINGS_LINKS,
  CURRENCIES,
  REPORTS_DATE,
};
